// <auto-generated />
namespace DemoApplication.Infrastructure.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Tasks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Tasks));
        
        string IMigrationMetadata.Id
        {
            get { return "201304211207570_Tasks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
