// <auto-generated />
namespace DemoApplication.Infrastructure.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Employees : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Employees));
        
        string IMigrationMetadata.Id
        {
            get { return "201304210539520_Employees"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
