using System;
using System.Collections.Generic;
using System.Text;

namespace DemoApplication.Areas.Api.MockData
{
    public class ModelRegistry
    {
        private static readonly List<Type> Data = new List<Type>
        {
            typeof(EmployeeBrief),
            typeof(TeamBrief),
            typeof(TemplateBrief)
        };

        public static Metadata Generate()
        {
            var metadata = new Metadata
            {
                MetadataVersion = "1.0.4",
                StructuralTypes = new List<StructuralType>(Data.Count)
            };

            foreach (var type in Data)
            {
                var structType = new StructuralType
                {
                    ShortName = type.Name,
                    Namespace = "Models",
                    AutoGeneratedKeyType = "None",
                    DataProperties = new List<DataProperty>()
                };

                foreach (var prop in type.GetProperties())
                {
                    structType.DataProperties.Add(new DataProperty
                    {
                        Name = ToCamelCase(prop.Name),
                        DataType = prop.PropertyType.Name,
                        IsNullable = !prop.PropertyType.IsValueType || (Nullable.GetUnderlyingType(prop.PropertyType) != null),
                        IsPartOfKey = prop.Name == "Id" ? true : false
                    });
                }

                metadata.StructuralTypes.Add(structType);
            }

            return metadata;
        }

        public class Metadata
        {
            public string MetadataVersion { get; set; }
            public List<StructuralType> StructuralTypes { get; set; }
        }

        public class StructuralType
        {
            public string ShortName { get; set; }
            public string Namespace { get; set; }
            public string AutoGeneratedKeyType { get; set; }

            public List<DataProperty> DataProperties { get; set; }
        }

        public class DataProperty
        {
            public string Name { get; set; }
            public string DataType { get; set; }
            public bool IsNullable { get; set; }
            public bool IsPartOfKey { get; set; }
        }

        private static string ToCamelCase(string s)
        {
            if (string.IsNullOrEmpty(s))
                return s;

            if (!char.IsUpper(s[0]))
                return s;

            var sb = new StringBuilder();
            for (int i = 0; i < s.Length; i++)
            {
                bool hasNext = (i + 1 < s.Length);
                if ((i == 0 || !hasNext) || char.IsUpper(s[i + 1]))
                {
                    char lowerCase;

                    lowerCase = char.ToLower(s[i]);
                    sb.Append(lowerCase);
                }
                else
                {
                    sb.Append(s.Substring(i));
                    break;
                }
            }

            return sb.ToString();
        }
    }
}